### ISSUE TITLE
How to inference the model after training?

### ISSUE THREAD

**Issue by canlinzhang** [ChristofHenkel/kaggle-asl-fingerspelling-1st-place-solution#1]
Hi:

Thank you for sharing the code. After training the model, they are saved to:
datamount/weights/cfg_2/fold-1/model.tflite 
datamount/weights/cfg_2/fold-1/inference_args.json

But then, how to inference the model? Or, how to use the model to predict a new keypoint sequence? Could you please provide the corresponding code? Thanks!

**Comment by ChristofHenkel** [comment]
How inference is done is shown here: https://www.kaggle.com/competitions/asl-fingerspelling/overview/evaluation
